name: Duolingo Stats
on:
  schedule: [{cron: "39 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  duolingo:
    name: Update readme with Duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: RichardKanshen/duolingo-readme-stats@main
        with:
          DUOLINGO_USER_ID: 745993669
          SHOW_FROM_ENGLISH: false
          ADVANCED_COOKIE: ${{ secrets.DUOLINGO }}
          SHOW_LEAGUE: true
